### PR TITLE
Add Atata

### PR DESCRIPTION
**Pull request by YevgeniyShunevych**
Added Atata framework to C# section.
[https://github.com/atata-framework/atata](https://github.com/atata-framework/atata)

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
👍🏻

**Comment by YevgeniyShunevych** [comment]
Hi Christian,

Could you please merge this pull request?

**Comment by christian-bromann** [comment]
Sorry I wasn't able to merge it with my phone due to build failure. Will do it now.

**Comment by YevgeniyShunevych** [comment]
Thanks!

**Pull request merged**
