### PR TITLE
Added Selenoid

### PR DESCRIPTION
**Pull request by vania-pooh**

### CODE REVIEW

**Comment by vania-pooh** [comment]
I think the build has failed because of another URL.

**Comment by dmitrytokarev** [comment]
@vania-pooh great tool! I saw your PR in awesome-docker - that list will be cleaned up to stay focused on more docker oriented projects.
I think your project belongs here rightfully. Probably you want to move it to the top of the Docker section to keep the list alphabetically sorted.

**Review by christian-bromann — APPROVED** [review]

**Comment by christian-bromann** [comment]
Thanks @vania-pooh

**Comment by dmitrytokarev** [comment]
@vania-pooh my bad, items in sections are not sorted alphabetically.
@christian-bromann do you think alphabetical order would make this awesome list even more awesome? ;)

**Comment by christian-bromann** [comment]
> do you think alphabetical order would make this awesome list even more awesome? ;)

Absolutely

**Comment by vania-pooh** [comment]
@dmitrytokarev I my opinion it's already in correct order. `Selenoid` is starting with `S` - so I placed it right after `D` and before `Z`. My goal is not to promote aerokube here. Correct me if something is wrong in my logic.

**Pull request merged**
